spring:
  cache:
    cache-names:
      - allEmployees
      - allDepartments
      - employeesByDepartment
      - employee
      - departments
      - employees
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
